{{ if .Values.ssh.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-ssh
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ssh.service.type }}
  ports:
    - port: {{ .Values.ssh.service.port }}
      targetPort: 8022
      protocol: TCP
      name: ssh
      {{ if eq .Values.ssh.service.type "NodePort" }}
      nodePort: {{ .Values.ssh.service.nodePort }}
      {{ end }}
  selector:
    app: {{ template "..name" . }}
    release: {{ .Release.Name }}
{{- end }}
