{{ if .Values.ssh.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub-ssh.ssh.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.ssh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ssh.service.type }}
  ports:
    - port: {{ .Values.ssh.service.port }}
      targetPort: 8022
      protocol: TCP
      name: ssh
      {{ if eq .Values.ssh.service.type "NodePort" }}
      nodePort: {{ .Values.ssh.service.nodePort }}
      {{ end }}
  selector:
    {{- include "jupyterhub-ssh.ssh.selectorLabels" . | nindent 4 }}
{{- end }}
