# Required to run
hostKey:

replicaCount: 1

image:
  repository: yuvipanda/jupyterhub-ssh-jupyterhub
  tag: '0.0.1-n020.hdebd61f'
  pullPolicy: Always

  name: yuvipanda/jupyterhub-ssh-jupyterhub
service:
  type: LoadBalancer
  port: 22
  nodePort: 32222

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  enabled: true

auth:
  type: github
  github:
    allowedUsers: []
