# Required to run
hostKey:

ssh:
  enabled: true

  replicaCount: 1

  image:
    repository: yuvipanda/jupyterhub-ssh-ssh
    tag: '0.0.1-n026.hf136ec7'
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 22

  resources: {}

  labels:
    hub.jupyter.org/network-access-proxy-http: "true"

  nodeSelector: {}

  tolerations: []

  affinity: {}



sftp:
  enabled: true
  replicaCount: 1


  pvc:
    name:

  image:
    repository: yuvipanda/jupyterhub-ssh-sftp
    tag: '0.0.1-n026.hf136ec7'
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 22

  resources: {}

  labels:
    hub.jupyter.org/network-access-proxy-http: "true"

  nodeSelector: {}

  tolerations: []

  affinity: {}
