# Required to run
hubUrl: ""
hostKey: ""

nameOverride: ""
fullnameOverride: ""

ssh:
  enabled: true
  replicaCount: 1

  image:
    repository: yuvipanda/jupyterhub-ssh-ssh
    tag: '0.0.1-n026.hf136ec7'
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 22

  podLabels:
    hub.jupyter.org/network-access-hub: "true"
    hub.jupyter.org/network-access-proxy-http: "true"
  podAnnotations: {}
  serviceLabels: {}
  serviceAnnotations: {}

  resources: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}



sftp:
  enabled: true
  replicaCount: 1

  # Not yet implemented. If we want this though, we should probably make sftp a
  # statefulset!
  pvc:
    name: ""

  image:
    repository: yuvipanda/jupyterhub-ssh-sftp
    tag: "0.0.1-n026.hf136ec7"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 22

  podLabels:
    hub.jupyter.org/network-access-hub: "true"
    hub.jupyter.org/network-access-proxy-http: "true"
  podAnnotations: {}
  serviceLabels: {}
  serviceAnnotations: {}

  resources: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
