kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jupyterhub-ssh.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.labels" . | nindent 4 }}
data:
  values.yaml: |
    {{- .Values | toYaml | nindent 4 }}
