kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub-ssh.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.labels" . | nindent 4 }}
type: Opaque
data:
  jupyterhub-ssh.host-key: {{ (required "hostKey must be set to a valid SSH Private key" .Values.hostKey) | b64enc | quote }}
