kind: Secret
apiVersion: v1
metadata:
  name: jupyterhub-ssh
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  jupyterhub-ssh.host-key: {{ (required "hostKey must be set to a valid SSH Private key" .Values.hostKey) | b64enc | quote }}
