kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub-ssh.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.labels" . | nindent 4 }}
type: Opaque
stringData:
  hubUrl: {{ .Values.hubUrl | required "hubUrl must be set to a valid JupyterHub URL" | quote }}
  hostKey: |
    {{- include "jupyterhub-ssh.hostKey" . | required "This should not happen: blank output from named template 'jupyterhub-ssh.hostKey'" | nindent 4 }}
  values.yaml: |
    {{- .Values | toYaml | nindent 4 }}
