{{- if .Values.sftp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupyterhub-ssh.sftp.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.sftp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sftp.replicaCount }}
  selector:
    matchLabels:
      {{- include "jupyterhub-ssh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jupyterhub-ssh.sftp.labels" . | nindent 8 }}
        hub.jupyter.org/network-access-hub: "true"
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      # We don't need any interaction with k8s API
      automountServiceAccountToken: false 
      volumes:
        - name: config
          secret:
            secretName: {{ include "jupyterhub-ssh.fullname" . }}
        - name: home
          persistentVolumeClaim:
            claimName: {{ .Values.sftp.pvc.name }}
      containers:
        - name: server
          image: "{{ .Values.sftp.image.repository }}:{{ .Values.sftp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sftp.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/jupyterhub-ssh/config
              readOnly: true
            - name: home
              mountPath: /mnt/home
          ports:
            - name: sftp
              containerPort: 2222
              protocol: TCP
          resources:
            {{- .Values.sftp.resources | toYaml | nindent 12 }}
      {{- with .Values.sftp.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.sftp.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.sftp.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
