{{- if .Values.sftp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupyterhub-ssh.sftp.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.sftp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sftp.replicaCount }}
  selector:
    matchLabels:
      {{- include "jupyterhub-ssh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jupyterhub-ssh.sftp.labels" . | nindent 8 }}
        {{- with .Values.sftp.podLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ omit .Values "ssh" | toYaml | sha256sum }}
        {{- with .Values.sftp.podAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      # We don't need any interaction with k8s API
      automountServiceAccountToken: false 
      volumes:
        {{- if .Values.sftp.pvc.enabled }}
        - name: home
          persistentVolumeClaim:
            claimName: {{ .Values.sftp.pvc.name }}
        {{- end }}
        # Selects only parts of the k8s Secret as a Volume. Note that we can
        # also specify a mode for individual files at this point, for example to
        # make the hostKey read only in the file system.
        #
        # ref: https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#secretvolumesource-v1-core
        - name: config
          secret:
            secretName: {{ include "jupyterhub-ssh.fullname" . }}
            items:
              - key: hostKey
                path: hostKey
                mode: 0400
              - key: hubUrl
                path: hubUrl
      containers:
        - name: server
          image: "{{ .Values.sftp.image.repository }}:{{ .Values.sftp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sftp.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
            {{- if .Values.sftp.pvc.enabled }}
            - name: home
              mountPath: /mnt/home
            {{- end }}
            - name: config
              mountPath: /etc/jupyterhub-sftp/config
              readOnly: true
          ports:
            - name: sftp
              containerPort: 2222
              protocol: TCP
          resources:
            {{- .Values.sftp.resources | toYaml | nindent 12 }}
      {{- with .Values.sftp.imagePullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.sftp.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.sftp.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.sftp.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
