{{ if .Values.sftp.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jupyterhub-sftp
  labels:
    app: {{ template "..name" . }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "..name" . }}
      release: {{ .Release.Name }}
      component: sftp-server
  policyTypes:
  - Ingress
  - Egress
  egress:
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # FIXME: This is way too permissive
  - to:
      - ipBlock:
          cidr: 0.0.0.0/0
  ingress:
  - from:
    - podSelector:
        matchLabels:
          hub.jupyter.org/network-access-sftp-server: "true"
    ports:
      - port: sftp
        protocol: TCP
{{- end }}
