{{- if .Values.sftp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub-ssh.sftp.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.sftp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sftp.service.type }}
  ports:
    - port: {{ .Values.sftp.service.port }}
      targetPort: 2222
      protocol: TCP
      name: sftp
      {{- if eq .Values.sftp.service.type "NodePort" }}
      nodePort: {{ .Values.sftp.service.nodePort }}
      {{- end }}
  selector:
    {{- include "jupyterhub-ssh.sftp.selectorLabels" . | nindent 4 }}
{{- end }}
