{{ if .Values.sftp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-sftp
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.sftp.service.type }}
  ports:
    - port: {{ .Values.sftp.service.port }}
      targetPort: 22
      protocol: TCP
      name: sftp
      {{ if eq .Values.sftp.service.type "NodePort" }}
      nodePort: {{ .Values.sftp.service.nodePort }}
      {{ end }}
  selector:
    app: {{ template "..name" . }}
    release: {{ .Release.Name }}
{{- end }}
